color: null
fieldLayouts:
  c04cbd38-1c4e-447e-8bd6-de19f916423d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T13:17:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d181eb54-0e5c-4e93-85bd-147f738ed9bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T13:19:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46d9a533-bd90-4c0c-9894-31b0e8502e04 # About title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66a7dec9-33b5-4800-bbe7-f432ce59ab8b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T13:19:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee5b4ae4-8d92-417a-b303-0583ffa2c50a # About text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a416f15a-3b42-4c74-8439-5d8275aa9a47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 038dc663-a485-4932-9534-d0bcad74a177
        userCondition: null
handle: aboutPage
hasTitleField: true
icon: null
name: 'About page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
