color: null
fieldLayouts:
  d3ce2463-4eed-4f3a-b6c3-abb0e5dc5193:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T15:16:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f39eef6b-29be-4056-a66f-fe916059e1d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T15:17:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b856c8d8-5706-4ebc-913c-61a7cadc96c8 # About title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99c83c3c-2f1a-4b6d-906d-14ddd6777f92
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T15:17:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee5b4ae4-8d92-417a-b303-0583ffa2c50a # About text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f7d4017-7952-4deb-a22d-fad5d97cf2fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a72202d-d774-4e4c-be33-c231827af448
        userCondition: null
handle: aboutPage
hasTitleField: true
icon: null
name: 'About page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
