color: cyan
fieldLayouts:
  d3ce2463-4eed-4f3a-b6c3-abb0e5dc5193:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T15:16:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f39eef6b-29be-4056-a66f-fe916059e1d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T08:53:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13df9399-bb4a-4a0d-a146-4f0da56af60f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T08:53:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Longtext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ff2eabb-27a9-4b79-b15d-19cfa710ba46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T09:15:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b2d1e2c2-b9cd-4e14-832e-787028e219d4
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8aee6e8-c982-47e9-87c1-cfc8c2fea05a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T10:14:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ab4eba5c-a169-4046-a357-2d5daee298f3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03267bc8-09fc-4a68-9231-1e7107d23079
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a72202d-d774-4e4c-be33-c231827af448
        userCondition: null
handle: aboutPage
hasTitleField: true
icon: address-card
name: 'About page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
