color: yellow
fieldLayouts:
  27fa79a9-715c-4028-a6b0-b96e19376763:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-09T19:22:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b5629c95-5797-4b3a-ba40-581229e9997b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:27:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef3cc2e5-d335-4281-ac71-957125422b66
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:25:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 898c34ed-4e55-459d-80ca-b0c21dd250f4 # Sfeerbeelden
            handle: sfeerImages
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68c01c2b-70f3-4675-8297-975b7a510564
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bbd76b33-7f1a-42ab-bda0-de989642444e
        userCondition: null
handle: beelden
hasTitleField: true
icon: image-landscape
name: Sfeerbeelden
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
