color: orange
fieldLayouts:
  535379d9-213d-47e4-8043-8223d1e44818:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-08T01:07:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3b0165a6-170a-47d1-a0d6-f0e72496696b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-08T01:34:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dc32a92-d905-495a-8cf3-4eb418ebf624
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-08T01:34:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfd662b1-329d-46ed-9ecd-766138668ae8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-08T01:34:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 74310f18-2e20-4c6b-9437-d6a029a0e09f
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fc26dc3-7596-417e-a31e-aff6164161ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1686cb05-5373-42b0-a091-ff947e479d67
        userCondition: null
handle: contactPage
hasTitleField: true
icon: address-card
name: 'Contact page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
