color: red
fieldLayouts:
  44c50e08-c428-491f-8b9d-a240eab7ccc4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-04T19:33:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 24320765-56b4-4bd9-b04f-e361f098c99a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-04T19:44:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Intro title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 054cf88a-0b1c-4b6c-8f4b-1383b8255fd9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-04T19:44:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Intro text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e40a93ee-d2e5-4fc7-be86-1fee440441f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-04T19:44:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4c69afaf-9769-4a03-8d42-bd62ee5efc20
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fefc7f50-95a6-48ce-a34e-35e30e452f19
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-04T19:44:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 74310f18-2e20-4c6b-9437-d6a029a0e09f # Adress
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3220c1ad-92c5-4168-b0fc-a37140a90571
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-04T19:44:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 22f25fbf-82ad-4650-8cc1-80fa7b6629f9 # map
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c17b75c-53e1-4be6-ad5b-f40074b0397b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0614fc60-1b04-45dc-93c1-5e89134ef306
        userCondition: null
handle: contact
hasTitleField: true
icon: address-card
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
