color: null
fieldLayouts:
  53360e7f-8af7-4592-b221-5eb4c076404e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-13T08:36:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f2f0247a-8d41-41bc-b6b3-6f1dab00174c # class
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97f0e3c8-1483-4526-94a4-700385abc500
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-12T13:39:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0f854ef1-d20b-4222-8d0a-0b9e6681610e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T14:29:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bf7984a-5ded-42a2-8c10-b514b5fabd78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T14:29:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d09af4db-7934-4a1f-95ff-8ca0906678d9 # maps
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63b59072-5b1e-4308-93c4-4b72a6a37ce3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T14:29:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47fffb00-da3c-4446-8b8b-9d72f0bd8f37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T14:29:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4265dbc7-a830-474d-8a3a-9aa9151007cd # Fotoâ€™s & Evenementen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4060ba40-4b28-47e1-8acc-87f242bb2483
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a7d7d6e-ab60-4b0f-a0b9-32e09a571a3c
        userCondition: null
handle: contact
hasTitleField: true
icon: address-book
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
