color: violet
fieldLayouts:
  217b418b-1f98-4e72-a25c-1369c713d0a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-11T17:56:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c9b56161-84d1-4629-b1b0-4c37d3c54ecd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T17:57:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90a21b64-c444-452e-bf64-b797dfd41200
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T17:57:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07aaa0f4-7a32-4cd6-bd2e-a702ceec7801
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T17:57:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f7e13fc-2e0c-489c-8239-296499e7c6ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: be0f2485-501b-4518-bc84-11159483a733
        userCondition: null
handle: facilitaireDiensten
hasTitleField: true
icon: shield
name: facilitaireDiensten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
