color: null
fieldLayouts:
  1cb17aba-5c09-4945-bba8-dea578b1e34b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-07T18:56:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e397f47-5e17-402a-897e-ac43ac73e8e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T20:30:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9638457d-dcf3-4651-b110-3afb116409da # Copyright Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 218777ae-63ca-487a-a53c-ef23fb2c1c32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T20:30:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 63899246-da1e-4152-aee2-ee8c4c9f6444 # facebook icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bad9862-23c4-47e8-8364-c8f46fa0a5ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T20:30:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17b5a972-9d05-4f34-8e24-d657d8972571 # facebook url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00ad4d44-7426-4a14-aa0f-de2b3aa1e24c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T20:30:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3159c64a-fcfa-403c-b4d7-95dcb1049954 # footer logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ff3614b-6fe3-45ca-b2d8-1d98437190df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T20:30:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 00f1c37f-44f1-4426-8679-4df2298cf426 # Footer Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a16675c-e637-4a10-bbc8-70276cfa6f8b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: af4ff200-872b-4c16-a077-74d3804e8f10
        userCondition: null
handle: footer
hasTitleField: true
icon: null
name: footer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
