color: null
fieldLayouts:
  088a4001-f93d-481a-a3a4-f24cc8b73d76:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-07T19:33:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 52e661af-be59-455e-9356-cb95e2aa090c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T19:36:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b3dc508e-66a7-46d8-8cba-e58656cc26c1 # nav label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39e5990e-8ecd-46de-a8eb-038a723d5a91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-07T19:36:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 98794487-2a00-4d81-9d35-cb811ece5b1c # nav target
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b333f06-8d4a-4354-a292-556a8f05a577
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: de20e3d9-2d93-4363-ab7e-05e3f75546d5
        userCondition: null
handle: footerNav
hasTitleField: true
icon: null
name: 'footer nav'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
