color: sky
fieldLayouts:
  cf28561b-56fa-4af7-95d6-80379b657cb2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-13T07:54:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f2f0247a-8d41-41bc-b6b3-6f1dab00174c # class
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99b586ff-23af-41ab-b041-074f14d8520d
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T14:51:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47fea052-d489-42e4-b598-ab54762d2611
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T01:47:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 56caabcb-9b95-4b2c-ba7a-4259d027bb03 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbf366b5-d355-4c24-8b54-8b62a7d5dc5e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T15:15:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8173f931-7055-46a1-8e5f-0d681be8bccf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T14:11:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6839763-0316-4acc-85b5-3d0995709da1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T08:51:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 016b5453-074e-4f2e-b01f-48292a0b6007
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5efdd8d6-6ea5-472e-ba59-10d3246b3775
        userCondition: null
handle: homePage
hasTitleField: true
icon: house
name: 'Home page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
