color: null
fieldLayouts:
  8fa0e1e5-3d4f-4615-8239-503d34c46820:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-16T14:03:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f5e4a86f-68fc-4a55-959c-0c00e53d2e94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T14:05:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d8b5f793-ddff-429f-840f-4943348961d6 # Intro title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c65a966-cd3c-4d1c-91a5-ac58eb1aaa53
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T14:05:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Intro text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16162751-73b7-470a-b64d-433635ddfe77
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 520c4326-4bca-4338-ad67-f2b63703ae19
        userCondition: null
handle: landingPage
hasTitleField: true
icon: null
name: 'Landing page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
