color: violet
fieldLayouts:
  92c2c585-f242-48c1-8114-0eee8dc76871:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-11T16:51:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7971f558-f9cf-48a4-9e57-2b3d5a4d2b17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T16:54:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fd33eb5-3371-41d4-9559-3a7880f2d031
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T16:54:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4a706de-acf2-4384-a3ac-044fe6573863
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T16:54:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55aed09c-f3af-4cff-9ea7-b3efa71fa331
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c555366b-b6d8-420d-814c-1758d0a0b292
        userCondition: null
handle: paramedish
hasTitleField: true
icon: shield-halved
name: paramedish
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
