color: blue
fieldLayouts:
  3fc15060-aa4b-47f1-9ce4-8ce06a35d827:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-10T15:05:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f66b8ec-a634-4bc3-979e-1402253178d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 56caabcb-9b95-4b2c-ba7a-4259d027bb03 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9053e98e-ba82-49c3-a76c-ab1cc2d7165e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dc656b5-ec32-4499-8216-7d681f59211d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71649979-9d1c-4fa4-905a-31126f8b5fd7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6416c1e5-1e51-4e74-8b2b-512504fd8ca1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5533870c-542f-4313-b708-e3e0de965c07
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd127dec-a11f-444c-afa0-088c2fa22a79
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: shortText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6471146a-db83-45c3-9a42-f021ae9e635e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: image2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0caaf5b-e77d-46f1-92e1-3f8c5d9ab642
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: image3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0de1f8e1-7724-41ab-9d6a-08ae4b345806
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 805410f1-5094-4d91-bcc1-677a8d297dad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: shortText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed83637a-e125-4be5-94e1-f431634026a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: image4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b70e2ca5-190f-4574-bb1f-391ffc42c280
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: image5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e9c7422-28df-447e-b491-6a65a377aebd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10cf22de-2e7f-4a61-be94-c4b2b5d0fc59
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: shortText4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e603c1f-a231-4f3b-bb08-4f1dd088d512
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: image6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27f280a6-b862-4205-9c34-b2e1c1fb8d7a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5564f55-c596-402c-b17f-fecaa7afe34e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:19:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: shortText5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a445b86f-36c6-42a9-b9e6-60791f9f0ec9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T15:29:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: image7
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79582710-8fb8-493d-88e4-c3f1af4802f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b88cd75-0f38-4852-b002-7bce5e0547b4
        userCondition: null
handle: projects
hasTitleField: true
icon: list-check
name: projects
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
