color: null
fieldLayouts:
  c857ecb5-46a7-4f13-8aa7-3a4386e875f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-09T00:16:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 73747283-2501-4b17-a00a-fc50721bdd30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T21:00:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 173b741a-f801-4574-8389-8f331484f4c4 # socials icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c07c89f-dc53-4709-8cb6-2e7a6937b843
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T21:00:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 04617b16-e0c7-4974-8865-b9224c05d067 # socials url
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 223ffd77-48d2-4fae-98e6-9ec817dd4958
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4c2cd3de-9d46-44bc-93d8-702ee271b9b8
        userCondition: null
handle: socials
hasTitleField: true
icon: null
name: socials
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
