color: orange
fieldLayouts:
  1f7de91a-4798-4b9a-8517-1fb3bcc096cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-06T09:10:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc7f1ad5-4c5d-43e7-9e40-8bfc5d6fa1f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T09:14:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48df56a7-5b7d-44b8-aff4-e12bf959f235
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T09:14:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b1486de-d233-4deb-a1c3-753f30c6fbe8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T09:14:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89088afa-2f5d-4dc9-a008-ae97bd8fbe90
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cc820b35-7500-4867-9a66-b62737d93dc7
        userCondition: null
handle: team
hasTitleField: true
icon: people
name: team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
