color: rose
fieldLayouts:
  bba5095b-af26-4e46-85a5-1699f95d4687:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-12T12:31:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 46c3b2b5-948d-4e8f-b1d2-827c03299ef6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 56caabcb-9b95-4b2c-ba7a-4259d027bb03 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3107021-007f-4849-a037-86929acddf97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b438d3c6-c617-4998-ae55-f81db134c68d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85c57fba-94b7-4e43-90c2-12b56c9399e3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Longtext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cc2b489-b649-4bed-bb18-cab1c156d614
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Longtext
            handle: longText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 397a0832-e696-44b7-9823-f983245300b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3784bd17-4458-4dce-9a2b-ca6755da9aea # Content Wonen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 300b2abf-7441-44bf-b6fe-8f4d8738d045
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4ecd4ec-cf31-4f24-98a2-9b123e8d7c4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:36:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 12e33af5-22e5-4810-a29a-4eafd0c140d5 # Zorgafbeeldingen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1e3f548-31df-4c66-8642-0ed83186403b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ef38c3f7-9239-4246-b54a-55da054b2f45
        userCondition: null
handle: wonen
hasTitleField: true
icon: igloo
name: Wonen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
