color: null
fieldLayouts:
  dec34cbd-4cec-4305-8ecb-0c78abacdebf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-09T18:42:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a3b0c1a0-4cee-4a31-9e88-877c2ac92651
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:39:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b9d46df-ec83-4743-80fe-f154f25e462d # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 578a83f8-e307-46a9-9355-9416137397ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:43:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5fb812b-3c30-40b5-8d89-a9ef03632fd7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T18:44:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Longtext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cb8466d-4092-4d60-9824-07f9535a35f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:43:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56c84f03-2019-4ee6-8744-a1ac42182775
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T18:44:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7367b22b-5f86-4e4a-9c93-77466dd30e97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:43:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77e71705-24c2-4c03-a5b8-0c7a7587d6a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T18:44:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: shortText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8577e28-2e1f-41b3-baa1-41e28c433f92
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:43:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2282cc48-3fa3-4e20-b4fc-581cbf713a8e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T18:44:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: shortText3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efab04d6-3799-4447-89e8-2c423de11b34
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T19:43:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: subheading5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f97f32e5-2625-4130-968c-3053a27fc385
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-09T18:44:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0127a613-d264-4c23-8aa4-4a4468b130c1 # Longtext
            handle: longText2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2bf941f-46c3-481f-a306-2081e4c21607
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68a9eb76-34a2-41c0-8a17-7681d19c0e9b
        userCondition: null
handle: zaalverhuur
hasTitleField: true
icon: null
name: Zaalverhuur
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
