color: violet
fieldLayouts:
  f00d1d0e-99a0-48a9-a29d-0bed8846c177:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-11T17:53:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 25ac14e2-3293-4097-b735-793c6c1074cf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T17:55:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76a23246-af09-477b-8f8a-a0712d042ebc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T17:56:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71dfc55b-3bc8-4b5e-8ae4-1b337105fffa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-11T17:55:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fa84003-7479-4e34-a848-868f1e1da685
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c0b1ae3-b7dd-4d1b-a1e4-f47678bbac06
        userCondition: null
handle: zorgteam
hasTitleField: true
icon: shield
name: zorgteam
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
