color: rose
fieldLayouts:
  6774a542-86db-423e-9e67-bbd095b26047:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-12T12:33:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a9d3b806-056a-4a32-9081-ff88c322682d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:35:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e8566ad4-3060-4438-9d37-aedb39f64380 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 632117fb-a608-4a78-90bd-83dccc283558
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:35:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbffd94e-0de3-4218-bbe5-cf69c6fc2b1f # Shorttext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67e8621b-bfef-498d-a14b-6974f997fb69
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:35:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 550744bc-0323-48c3-aad2-7f5010e23275 # image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cb321a3-8f2f-4e41-b1c1-6d7faccf2249
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dfc1c6dd-7170-4f09-84df-e550aec2317a
        userCondition: null
handle: zorgafbeeldingen
hasTitleField: true
icon: staff-snake
name: Zorgafbeeldingen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
