altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  256b2940-0229-4e12-bf17-1d3a8baeed75:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T08:47:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ede4a7b0-7094-4edf-aede-7e0cbc625b7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 728d9683-fa4e-4875-86b8-5da7a3947ff0
        userCondition: null
fs: sintColeta
handle: sintColeta
name: sint-coleta
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
