columnSuffix: null
handle: shortText
instructions: null
name: Shorttext
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: ddda41dd-0f46-478b-adf6-e0993e3401a0 # Simple
  createButtonLabel: null
  defaultTransform: null
  fullGraphqlData: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
