dateModified: 1748890517
email:
  fromEmail: akg@gmail.com
  fromName: 'multisite cms'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  cultuurColette:
    hasUrls: true
    name: 'cultuur colette'
    settings:
      path: '@webroot/assets/colette'
    type: craft\fs\Local
    url: '@web/assets/colette'
  mariahuis:
    hasUrls: true
    name: mariahuis
    settings:
      path: '@webroot/assets/mariahuis'
    type: craft\fs\Local
    url: '@web/assets/mariahuis'
  sintColeta:
    hasUrls: true
    name: sint-coleta
    settings:
      path: '@webroot/assets/sint-coleta'
    type: craft\fs\Local
    url: '@web/assets/sint-coleta'
meta:
  __names__:
    00c2fcb6-5095-4aa4-bb09-5edc3ed1980d: 'cultuur colette' # cultuur colette
    7a2a5b69-b8c1-4f5d-8724-8c3fb08cd9c5: 'Home page' # Home page
    7d87d3c0-9b0a-42f6-9032-c230f824d597: 'Home page' # Home page
    7f3f813f-d9de-4c1d-ba53-88f8dde03240: nav-structuur # nav-structuur
    8b9d46df-ec83-4743-80fe-f154f25e462d: 'Intro title' # Intro title
    8da6550d-2ca9-4aed-b45f-b6bd92e697b9: 'Nav Entry' # Nav Entry
    43b28afb-ae43-4b46-b1c8-7dee1b3c0fb8: 'multisite cms' # multisite cms
    78dc517e-e56c-4f2b-bca5-162c82ba4d20: 'Nav Structuur' # Nav Structuur
    0127a613-d264-4c23-8aa4-4a4468b130c1: 'Intro text' # Intro text
    182d7633-959a-49a7-ac3b-dc6004c59e14: 'About page' # About page
    2586cd74-aa98-4355-81dd-4d3226fe9650: Sint-Coleta # Sint-Coleta
    7094e591-417f-42d9-ac11-3ab0286ae513: 'Cultuur Colette' # Cultuur Colette
    574815ea-8309-4923-b4ef-27d7dd272184: sint-coleta # sint-coleta
    8285487f-7dd3-4533-a52d-bf5cc442aeb4: Mariahuis # Mariahuis
    ab4ac2b8-0348-490e-a1d8-c02351505b0c: 'About page' # About page
    afe0a74f-2dfe-44d2-982d-34c9dffa564b: 'Nav Label' # Nav Label
    b856c8d8-5706-4ebc-913c-61a7cadc96c8: 'About title' # About title
    bbd32f72-a7c4-4248-8b85-fb976daf52ef: 'Public Schema' # Public Schema
    ddda41dd-0f46-478b-adf6-e0993e3401a0: Simple # Simple
    e3b18acb-2d5b-4c4c-a437-f2cfff04562d: mariahuis # mariahuis
    ee5b4ae4-8d92-417a-b303-0583ffa2c50a: 'About text' # About text
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: 'multisite cms'
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
