defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8594e9b5-caf2-4d4c-abcc-c6c2c5c3e87f # Contribute
handle: contribute
maxAuthors: 1
name: Contribute
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2586cd74-aa98-4355-81dd-4d3226fe9650: # Sint-Coleta
    enabledByDefault: true
    hasUrls: true
    template: _pages/_contribute.twig
    uriFormat: contribute
  8285487f-7dd3-4533-a52d-bf5cc442aeb4: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _pages/_contribute.twig
    uriFormat: contribute
type: single
