defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 21397684-5941-4452-abb8-931f54e0f6cb # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2586cd74-aa98-4355-81dd-4d3226fe9650: # Sint-Coleta
    enabledByDefault: true
    hasUrls: true
    template: _pages/_contact.twig
    uriFormat: contact
  7094e591-417f-42d9-ac11-3ab0286ae513: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: _pages/_contact.twig
    uriFormat: contact
  8285487f-7dd3-4533-a52d-bf5cc442aeb4: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _pages/_contact.twig
    uriFormat: contact
type: single
