defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ef5f8ffc-db4a-4bde-be4c-dd9764883dc1 # footer nav
handle: footernav
maxAuthors: 1
name: footerNav
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  2586cd74-aa98-4355-81dd-4d3226fe9650: # Sint-Coleta
    enabledByDefault: true
    hasUrls: true
    template: footernav/_entry.twig
    uriFormat: 'footernav/{slug}'
  7094e591-417f-42d9-ac11-3ab0286ae513: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: footernav/_entry.twig
    uriFormat: 'footernav/{slug}'
  8285487f-7dd3-4533-a52d-bf5cc442aeb4: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: footernav/_entry.twig
    uriFormat: 'footernav/{slug}'
structure:
  maxLevels: null
  uid: 1e758105-df23-4169-a582-1758d1a4bd8d
type: structure
