defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1f9192f7-ec38-4f89-863f-79ade97b04fa # navItems
handle: navstructuur
maxAuthors: 1
name: NavStructuur
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  2586cd74-aa98-4355-81dd-4d3226fe9650: # Sint-Coleta
    enabledByDefault: true
    hasUrls: true
    template: navstructuur/_entry.twig
    uriFormat: 'navstructuur/{slug}'
  7094e591-417f-42d9-ac11-3ab0286ae513: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: navstructuur/_entry.twig
    uriFormat: 'navstructuur/{slug}'
  8285487f-7dd3-4533-a52d-bf5cc442aeb4: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: navstructuur/_entry.twig
    uriFormat: 'navstructuur/{slug}'
structure:
  maxLevels: null
  uid: 301fcbd6-cab9-4c43-9347-92e66c3f942b
type: structure
