defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7f3f813f-d9de-4c1d-ba53-88f8dde03240 # nav-structuur
handle: navStructuur
maxAuthors: 1
name: 'Nav Structuur'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2586cd74-aa98-4355-81dd-4d3226fe9650: # Sint-Coleta
    enabledByDefault: true
    hasUrls: true
    template: _partials/_header.twig
    uriFormat: 'nav-structuur/{slug}'
  7094e591-417f-42d9-ac11-3ab0286ae513: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: _partials/_header.twig
    uriFormat: 'nav-structuur/{slug}'
  8285487f-7dd3-4533-a52d-bf5cc442aeb4: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _partials/_header.twig
    uriFormat: 'nav-structuur/{slug}'
structure:
  maxLevels: null
  uid: bd5d9cc1-a5d5-4d4c-bb8c-9820c01f53cc
type: structure
