defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 381a0bc4-0f70-4126-b52a-b7e8d8cbbe43 # projects
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2586cd74-aa98-4355-81dd-4d3226fe9650: # Sint-Coleta
    enabledByDefault: true
    hasUrls: true
    template: _pages/_project.twig
    uriFormat: projects
  8285487f-7dd3-4533-a52d-bf5cc442aeb4: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _pages/_project.twig
    uriFormat: projects
type: single
